### ISSUE TITLE
pip install STHD can not install

### ISSUE THREAD

**Issue by honghh2018** [yi-zhang/STHD#1]
Hi  developer,
    I want to  test my HD visium data to install the STHD , but  it  show me below information
    $pip install STHD
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement STHD (from versions: none)
ERROR: No matching distribution found for STHD

It can not be installed by pip ?
Best wish,
any advices would be appreciated
hanhuihong

**Comment by honghh2018** [comment]
Had anyone hear this issue?

**Comment by yi-zhang** [comment]
Hi Hanhui,
We are still finalizing the software, so will release the stable version to pip soon with more detailed stepwise tutorials. For now it can be used by git cloning as instructed in README.md, for example,`git clone git@github.com:yi-zhang/STHD.git`. Thanks!
