### ISSUE TITLE
No such file or directory: '/square_002um/spatial/tissue_positions_list.csv'

### ISSUE THREAD

**Issue by HenryJinZH** [yi-zhang/STHD#2]
Hi developer,
When runing 
    full_data = sthdio.STHD(
        spatial_path = hd_data_square_002um_path, 
        counts_data = 'filtered_feature_bc_matrix.h5', 
        full_res_image_path = hd_fullres_img_btf_path, 
        load_type = 'original'
    )
I get a error message end with this:
    FileNotFoundError: [Errno 2] No such file or directory: '../crc_hd/Human_Colon_Cancer_P1/square_002um/spatial/tissue_positions_list.csv'
I think it's caused by an updated vervion of spaceranger, but I don't know fix it.
Best wish

**Comment by yi-zhang** [comment]
Hi Henry,
Yes the original tissue_positions file is in parquet format and conversion to csv is needed for now. We provided a simple function in STHD/hdpp.py for this: `python hdpp.py --spatialdir <your_folder_square_002um>`
