### ISSUE TITLE
.btf image

### ISSUE THREAD

**Issue by Jammm11** [yi-zhang/STHD#4]
Hi developer,
I want to know how can I get full-resolution H&E **.btf** image. It is not present in my raw sequencing data and the output of spaceranger. 
Is this a HE image with the fiducial frame? The image in demo is too big to open for preview.

**Comment by Sophieliula** [comment]
This picture is an output from  microscope scan and also is an input file for running spaceranger.

**Comment by yi-zhang** [comment]
This would be the full-resolution microscope image, usually a big separate image file and also the same microscope image input in spaceranger. Example is at https://www.10xgenomics.com/datasets/visium-hd-cytassist-gene-expression-libraries-of-human-crc.

**Comment by Jinjin89** [comment]
@yi-zhang 
Hi, really great work here.
I could not get the full-resolution microscope image for my analysis. Could I use the high reslution img instead?
