### ISSUE TITLE
Is it possible to run without reference file?

### ISSUE THREAD

**Issue by ZhengJIN94** [yi-zhang/STHD#5]
Hi, 

I want to run STHD to segmentation my Visium HD data, however, I cannot find suitable scRNA-seq data to use as a reference.

Is it possible to run the algorithm without providing a reference file?

Thank you.

**Comment by yi-zhang** [comment]
Hi Zheng, a reference scRNAseq is required for now, since the STHD model needs to learn gene expression pattern of various cell types in your system. We are actively improving and please contact if there are features in high needs. Thanks!
